import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/websiteSecurity.css";
import "../styles/watermark.css";
import WebsiteSecurity from "../security/WebsiteSecurity";
import Watermark from "../security/Watermark";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"],});
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"],});
export const metadata = { title: "RWITC", description: "Generated by create next app",};
export default function RootLayout({ children }) {
    return (

        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                    {/* Website Security */}
                    <WebsiteSecurity />
                    {/* Watermark */}
                    <Watermark />
                    {/* All Pages */}
                    {children}
            </body>
        </html>
    );
}